/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package de.appwerft.ringtonmanager;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;

import android.app.Activity;
import android.os.Build;
import java.io.File;
import android.content.ContentValues;
import android.content.Context;
import android.provider.MediaStore;
import android.net.Uri;
import android.media.RingtoneManager;

import android.provider.Settings;
import android.provider.Settings.System;
import android.content.Intent;
//import android.content.pm.PackageManager;

@Kroll.module(name="Tiringtonemanager", id="de.appwerft.ringtonmanager")
public class TiringtonemanagerModule extends KrollModule {

	// Standard Debugging variables
	private static final String LCAT = "TiringtonemanagerModule";
	private static final boolean DBG = TiConfig.LOGD;


	public TiringtonemanagerModule() {
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)	{
		Log.d(LCAT, "inside onAppCreate");
	}

	// Methods
	
    private void setRingtone(Uri uri) {
        Activity currentActivity = TiApplication.getInstance().getCurrentActivity();
        RingtoneManager.setActualDefaultRingtoneUri(
                currentActivity,
                RingtoneManager.TYPE_RINGTONE,
                uri
        );
    }
    
    
    @Kroll.method
	public void setActualDefaultRingtone(String filepath) {
        
        File k = new File(filepath);
        ContentValues values = new ContentValues();
        values.put(MediaStore.MediaColumns.DATA, k.getAbsolutePath());
        values.put(MediaStore.MediaColumns.TITLE, "Ringtone");
        values.put(MediaStore.MediaColumns.SIZE, 215454); // how can I determine?
        values.put(MediaStore.MediaColumns.MIME_TYPE, "audio/mp3");
        values.put(MediaStore.Audio.Media.ARTIST, "NoArtist");
        values.put(MediaStore.Audio.Media.DURATION, 230); // how can I determine?
        values.put(MediaStore.Audio.Media.IS_RINGTONE, true);
        values.put(MediaStore.Audio.Media.IS_NOTIFICATION, false);
        values.put(MediaStore.Audio.Media.IS_ALARM, false);
        values.put(MediaStore.Audio.Media.IS_MUSIC, false);
        
        //Insert it into the database
        Uri uri = MediaStore.Audio.Media.getContentUriForPath(k.getAbsolutePath());
        Uri newUri = getActivity().getContentResolver().insert(uri, values);

        boolean canDo =  android.provider.Settings.System.canWrite(TiApplication.getInstance());
        if (false == canDo) {
            Intent grantIntent = new Intent(Settings.ACTION_MANAGE_WRITE_SETTINGS);
            startActivity(grantIntent);
        } else {
            setRingtone(newUri);

        }
        
    }
}

